{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: sd
spec:
  {{- if or .Values.ingress.automatic1111.tls.enabled .Values.ingress.comfy.tls.enabled }}
  tls:
  - hosts:
      {{- if .Values.ingress.automatic1111.tls.enabled }}
      - {{ .Values.ingress.automatic1111.host }}
      {{- end }}
      {{- if .Values.ingress.comfy.tls.enabled }}
      - {{ .Values.ingress.comfy.host }}
      {{- end }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    {{- if .Values.automatic1111.enabled }}
    - host: {{ .Values.ingress.automatic1111.host }}
      http:
        paths:
          - backend:
              service:
                name: sd
                port:
                  number: 8080
            path: /
            pathType: Prefix
    {{- end }}
    {{- if .Values.comfy.enabled }}
    - host: {{ .Values.ingress.comfy.host }}
      http:
        paths:
          - backend:
              service:
                name: sd
                port:
                  number: 8081
            path: /
            pathType: Prefix
    {{- end }}
{{- end }}
