kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: sonarr
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/stable-diffusion-builder-kubernetes.git
  targets:
    - name: ai
      clusterSelector:
        matchLabels:
          cluster: ai
  paths:
    - ./kubernetes
