comfy:
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"

automatic1111:
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"

useCpu: false

models:
  links: |
    https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
      out=Stable-diffusion/v1-5-pruned-emaonly.ckpt
    https://huggingface.co/nicky007/stable-diffusion-logo-fine-tuned/resolve/main/train.ckpt
      out=Stable-diffusion/diffusion-logo-fine-tuned.ckpt
    https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt
      out=VAE/vae-ft-mse-840000-ema-pruned.ckpt
    https://huggingface.co/runwayml/stable-diffusion-inpainting/resolve/main/sd-v1-5-inpainting.ckpt
      out=Stable-diffusion/sd-v1-5-inpainting.ckpt
    https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth
      out=GFPGAN/GFPGANv1.4.pth
    https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth
      out=RealESRGAN/RealESRGAN_x4plus.pth
    https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth
      out=RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
    https://heibox.uni-heidelberg.de/f/31a76b13ea27482981b4/?dl=1
      out=LDSR/project.yaml
    https://heibox.uni-heidelberg.de/f/578df07c8fc04ffbadf3/?dl=1
      out=LDSR/model.ckpt
    https://huggingface.co/imagepipeline/RealVisXL-V4-V4-BakedVAE/resolve/main/vae/diffusion_pytorch_model.fp16.safetensors
      out=VAE/RealVisXL-V4-BakedVAE.safetensors
    https://civitai.com/api/download/models/344487?type=Model&format=SafeTensor&size=pruned&fp=fp16
      out=Stable-diffusion/realvis.safetensors
    https://civitai.com/api/download/models/1224?type=Model&format=PickleTensor&size=full&fp=fp16
      out=Stable-diffusion/f222_v1.ckpt

  checksums: |
    cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516  /data/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
    c6bbc15e3224e6973459ba78de4998b80b50112b0ae5b5c67113d56b4e366b19  /data/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
    c6a580b13a5bc05a5e16e4dbb80608ff2ec251a162311590c1f34c013d7f3dab  /data/models/VAE/vae-ft-mse-840000-ema-pruned.ckpt
    e2cd4703ab14f4d01fd1383a8a8b266f9a5833dacee8e6a79d3bf21a1b6be5ad  /data/models/GFPGAN/GFPGANv1.4.pth
    4fa0d38905f75ac06eb49a7951b426670021be3018265fd191d2125df9d682f1  /data/models/RealESRGAN/RealESRGAN_x4plus.pth
    f872d837d3c90ed2e05227bed711af5671a6fd1c9f7d7e91c911a61f155e99da  /data/models/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth
    c209caecac2f97b4bb8f4d726b70ac2ac9b35904b7fc99801e1f5e61f9210c13  /data/models/LDSR/model.ckpt
    9d6ad53c5dafeb07200fb712db14b813b527edd262bc80ea136777bdb41be2ba  /data/models/LDSR/project.yaml
    6353737672c94b96174cb590f711eac6edf2fcce5b6e91aa9d73c5adc589ee48  /data/models/VAE/RealVisXL-V4-BakedVAE.safetensors
    912c9dc74f5855175c31a7993f863a043ac8dcc31732b324cd05d75cd7e16844  /data/models/Stable-diffusion/realvis.safetensors
