models:
  image: harbor.atoy.dev/public/stablediffusion/download:latest
  reclaimPolicy: Retain
  capacity: 10Gi
  storageClass: ""
  pullPolicy: IfNotPresent
  links: |
    https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
      out=Stable-diffusion/v1-5-pruned-emaonly.ckpt

service:
  type: ClusterIP

ingress:
  enabled: true
  automatic1111Host: automatic.atoy.lol
  comfyHost: comfy.atoy.lol

comfy:
  image: harbor.atoy.dev/public/stablediffusion/comfy:latest
  resources: {}
  enabled: true
  cli_args:
    - --port
    - "8081"
automatic1111:
  image: harbor.atoy.dev/public/stablediffusion/automatic:latest
  resources: {}
  enabled: true
  cli_args:
    - --port
    - "8080"

useCpu: true

