models:
  image: harbor.atoy.dev/public/stablediffusion/download:latest
  reclaimPolicy: Retain
  capacity: 50Gi
  storageClass: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: true
  automatic1111Host: automatic.atoy.lol
  comfyHost: comfy.atoy.lol

comfy:
  image: harbor.atoy.dev/public/stablediffusion/comfy:latest
  resources: {}
  enabled: true
  cli_args:
    - --port
    - "8081"
automatic1111:
  image: harbor.atoy.dev/public/stablediffusion/automatic:latest
  resources: {}
  enabled: true
  cli_args:
    - --port
    - "8080"

useCpu: true
