name: Build Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log into Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login ${{ var.DOCKER_REGISTRY }} -u $DOCKER_USER --password-stdin

      - name: Build Download
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./services/download
          file: ./services/download/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ var.DOCKER_REGISTRY }}/public/stablediffusion/download:latest

      - name: Build AUTOMATIC
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./services/AUTOMATIC1111
          file: ./services/AUTOMATIC1111/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ var.DOCKER_REGISTRY }}/public/stablediffusion/automatic:latest

      - name: Build Comfy
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./services/comfy
          file: ./services/comfy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ var.DOCKER_REGISTRY }}/public/stablediffusion/comfy:latest
